apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  selector:
      app: wordpress
      tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

