apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: mysql
    tier: wordpress
spec:


  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend

  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      volumes:
        - name: wordpress-vol
          persistentVolumeClaim:
            claimName: wordpress-pvc      
      containers:
      - name: wordpress
        image: wordpress:php7.1-apache
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wordpress-vol
          mountPath: "/var/www/html"
        env:
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: mysql-password
        - name: WORDPRESS_DB_HOST
          value: mysql-svc
